#!/usr/bin/env python3
"""Extract translatable UI strings from the Go source into a gettext .pot
template (po/ui/immortal-barons.pot).

The game localizes UI strings through a small set of call sites, so we scan for
their string-literal arguments:

  - tr(s, "...")                      direct-print helper
  - ok(s, "..." / fail via errors     feedback
  - prompt / promptInt / promptSuggested / askYesNo / askYesNoDefaultNo
  - i18n.T(lang, "...")               explicit lookups (menu draw)
  - menu item Label:/Title: literals  menu chrome
  - errors.New("...") in internal/game  (surfaced to the player via fail())

This is a translation-time helper only — not part of the build. Run it after
adding new strings, then fill in msgstr in internal/i18n/locale/<lang>.po.
Untranslated strings fall back to English at runtime, so the .pot is a
convenience for translators, not a build gate.
"""
import re
import os
import glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# A Go interpreted string literal (no raw backtick strings; those aren't used
# for UI text). Captures the inner bytes with escapes intact.
STR = r'"((?:[^"\\]|\\.)*)"'

CALL_PATTERNS = [
    re.compile(r'\btr\(s,\s*' + STR),
    re.compile(r'\bi18n\.T\([^,]+,\s*' + STR),
    re.compile(r'\bok\(s,\s*' + STR),
    re.compile(r'\bprompt\(s,\s*' + STR),
    re.compile(r'\bpromptInt\(s,\s*' + STR),
    re.compile(r'\bpromptSuggested\(s,\s*' + STR),
    re.compile(r'\baskYesNo\(s,\s*' + STR),
    re.compile(r'\baskYesNoDefaultNo\(s,\s*' + STR),
    re.compile(r'\bstatLine\(s,\s*[^,]+,\s*' + STR),
    re.compile(r'\b(?:Label|Title):\s*' + STR),
]
ERR_PATTERN = re.compile(r'errors\.New\(' + STR + r'\)')

def go_files(*subdirs):
    for sub in subdirs:
        for path in glob.glob(os.path.join(ROOT, sub, "**", "*.go"), recursive=True):
            if path.endswith("_test.go"):
                continue
            yield path

def extract():
    seen = {}  # msgid -> first "file:line"
    def add(mid, loc):
        if mid and mid not in seen:
            seen[mid] = loc
    for path in go_files("internal/menu"):
        rel = os.path.relpath(path, ROOT)
        for n, line in enumerate(open(path, encoding="utf-8"), 1):
            for pat in CALL_PATTERNS:
                for m in pat.finditer(line):
                    add(m.group(1), f"{rel}:{n}")
    for path in go_files("internal/game"):
        rel = os.path.relpath(path, ROOT)
        for n, line in enumerate(open(path, encoding="utf-8"), 1):
            for m in ERR_PATTERN.finditer(line):
                add(m.group(1), f"{rel}:{n}")
    return seen

def main():
    seen = extract()
    out = os.path.join(ROOT, "po", "ui", "immortal-barons.pot")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write('# Immortal Barons UI strings — extraction template.\n')
        f.write('# Generated by scripts/gen-ui-pot.py. Fill msgstr in\n')
        f.write('# internal/i18n/locale/<lang>.po (same msgid).\n')
        f.write('msgid ""\nmsgstr ""\n'
                '"Content-Type: text/plain; charset=UTF-8\\n"\n\n')
        for mid in sorted(seen):
            f.write(f'#: {seen[mid]}\n')
            f.write(f'msgid "{mid}"\n')
            f.write('msgstr ""\n\n')
    print(f"wrote {out} ({len(seen)} strings)")

if __name__ == "__main__":
    main()
