#!/usr/bin/env python3
"""Extract translatable UI strings from the Go source into a gettext .pot
template (po/ui/immortal-barons.pot).

The game localizes UI strings through a small set of call sites, so we scan for
their string-literal arguments:

  - tr(s, "...")                      direct-print helper
  - plural(s, n, "one", "many")       both wordings of a counted figure
  - ok / okNoPause(s, "..." / fail via errors     feedback
  - prompt / promptInt / promptSuggested(Tight) / AskYesNo / askYesNoHere
  - i18n.T(lang, "...")               explicit lookups (menu draw)
  - menu item Label:/Title: literals  menu chrome
  - errors.New("...") in internal/game  (surfaced to the player via fail())
  - typed op constants in internal/game whose value IS a menu label

This is a translation-time helper only — not part of the build. Run it after
adding new strings, then fill in msgstr in internal/i18n/locale/<lang>.po.
Untranslated strings fall back to English at runtime, so the .pot is a
convenience for translators, not a build gate.
"""
import re
import os
import glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# A Go interpreted string literal (no raw backtick strings; those aren't used
# for UI text). Captures the inner bytes with escapes intact.
STR = r'"((?:[^"\\]|\\.)*)"'

CALL_PATTERNS = [
    re.compile(r'\btr\(s,\s*' + STR),
    re.compile(r'\bi18n\.T\([^,]+,\s*' + STR),
    re.compile(r'\bok\(s,\s*' + STR),
    re.compile(r'\bokNoPause\(s,\s*' + STR),
    re.compile(r'\bprompt\(s,\s*' + STR),
    re.compile(r'\bpromptInt\(s,\s*' + STR),
    re.compile(r'\bpromptSuggested\(s,\s*' + STR),
    re.compile(r'\bpromptSuggestedTight\(s,\s*' + STR),
    re.compile(r'\bAskYesNo\(s,\s*' + STR),
    re.compile(r'\baskYesNoHere\(s,\s*' + STR),
    re.compile(r'\bstatLine\(s,\s*[^,]+,\s*' + STR),
    re.compile(r'\b(?:Label|Title):\s*' + STR),
    re.compile(r'\bonOff\(' + STR),  # Preferences toggle labels (dynamic LabelFn)
]
ERR_PATTERN = re.compile(r'errors\.New\(' + STR + r'\)')

# internal/game writes some player-visible text itself (battle reports, the
# events it files on the other player's recap). It cannot import internal/menu,
# so it translates through a local tr() closure or i18n.T keyed on the empire's
# own Language — neither of which the menu-side patterns above match.
# A menu item whose label comes from the constant it dispatches on (the covert
# ops) has no literal left in internal/menu for the Label: pattern to find, so
# the constant's own declaration is the msgid.
GAME_PATTERNS = [
    re.compile(r'\bCovertOp\s*=\s*' + STR),
    re.compile(r'\btr\(' + STR),
    re.compile(r'\bi18n\.T\([^,]+,\s*' + STR),
]

# plural(s, n, "one", "many") carries BOTH wordings, and the count argument may
# itself contain commas (math.Max(1, ...)), so match the last two literals in
# the call rather than counting arguments.
PLURAL_PATTERN = re.compile(r'\bplural\(s,.*?' + STR + r',\s*' + STR + r'\)')

def go_files(*subdirs):
    for sub in subdirs:
        for path in glob.glob(os.path.join(ROOT, sub, "**", "*.go"), recursive=True):
            if path.endswith("_test.go"):
                continue
            yield path

def extract():
    seen = {}  # msgid -> first "file:line"
    def add(mid, loc):
        if mid and mid not in seen:
            seen[mid] = loc
    # internal/menu is the bulk of the UI; internal/play holds the first-run
    # onboarding text; cmd holds the -help/usage strings (flag descriptions wrapped
    # in i18n.T so they translate to the locale).
    for path in go_files("internal/menu", "internal/play", "cmd"):
        rel = os.path.relpath(path, ROOT)
        for n, line in enumerate(open(path, encoding="utf-8"), 1):
            for pat in CALL_PATTERNS:
                for m in pat.finditer(line):
                    add(m.group(1), f"{rel}:{n}")
            for m in PLURAL_PATTERN.finditer(line):
                add(m.group(1), f"{rel}:{n}")
                add(m.group(2), f"{rel}:{n}")
    for path in go_files("internal/game"):
        rel = os.path.relpath(path, ROOT)
        for n, line in enumerate(open(path, encoding="utf-8"), 1):
            for m in ERR_PATTERN.finditer(line):
                add(m.group(1), f"{rel}:{n}")
            for pat in GAME_PATTERNS:
                for m in pat.finditer(line):
                    add(m.group(1), f"{rel}:{n}")
    return seen

def main():
    seen = extract()
    out = os.path.join(ROOT, "po", "ui", "immortal-barons.pot")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write('# Immortal Barons UI strings — extraction template.\n')
        f.write('# Generated by scripts/gen-ui-pot.py. Fill msgstr in\n')
        f.write('# internal/i18n/locale/<lang>.po (same msgid).\n')
        f.write('msgid ""\nmsgstr ""\n'
                '"Content-Type: text/plain; charset=UTF-8\\n"\n\n')
        for mid in sorted(seen):
            f.write(f'#: {seen[mid]}\n')
            f.write(f'msgid "{mid}"\n')
            f.write('msgstr ""\n\n')
    print(f"wrote {out} ({len(seen)} strings)")

if __name__ == "__main__":
    main()
